### ISSUE TITLE
Gives inf ranges and no intensities

### ISSUE THREAD

**Issue by Rudresh172** [mich1342/ros2_laser_scan_merger#10]
Ubuntu 22.04 
ROS Humble

I have 2 Sick nanoScan3 laser scanners mounted on diagonally opposite sides of the mobile robot. The laser scanner uses a ROS1 driver (since there is a ROS1 computer in the mobile robot) and it gets transferred to ROS2 via a bridge. I can see the individual scans in Rviz2 - 
![scan_merger_error2](https://github.com/mich1342/ros2_laser_scan_merger/assets/93994789/29f7eca2-d7c5-4607-9832-f1e78fee646a)

Now when I use the merger, the ranges show inf and the intensities list is empty - 
![scan_merger_error](https://github.com/mich1342/ros2_laser_scan_merger/assets/93994789/618ca3df-1bee-4a92-833b-c03987fb300d)

Here is the echo of the /f_scan - 
![scan_merger_error_f_scan](https://github.com/mich1342/ros2_laser_scan_merger/assets/93994789/0f885d2f-cde5-4f2f-9b3b-dac67ead8fe8)
I also tried changing the values according to the /f_scan, but still the same result - 
![Screenshot from 2023-12-07 15-39-57](https://github.com/mich1342/ros2_laser_scan_merger/assets/93994789/04eae578-81e0-4c9a-bcd9-c5b3daaf846c)

I'm fairly new, so cannot find out the exact issue. Can you please elaborate on some of the param values like laser1Alpha, laser1XOff, inf_epsilon, etc. Maybe I might have configured it incorrectly.

Thanks!

**Comment by mich1342** [comment]
Hi @Rudresh172,

I think your problem is your frame id, both of the topic should be in laser topic. This package creates a virtual Lidar. You do not need to put frame id and define the tf for both of your lidars. This package does it for you and publishing as if you have a single lidar.

Try to change both your raw lidar data frame id into laser.

For the intensity it is empty because this package merge based on distance interpolation between two adjacent scan. There is no way to interpolate two intensities so i left it blank.

**Comment by Rudresh172** [comment]
Hey @mich1342,

Thanks for your quick response! I changed the frame id of both the raw scans to laser, but it's still the same issue.
 
![scan_merger_error_11](https://github.com/mich1342/ros2_laser_scan_merger/assets/93994789/3051f632-7d6e-4568-b3af-e9242eab6e74)
The top window has one of the raw scan with changed frame id. When I changed the pointCloudFrameId to laser, the queue was getting full, so I changed it back to base_link. Is there any other param that's set incorrectly? 

Also, should the angles be in degrees or radians? The raw scans have it in radians, so I changed it here accordingly. The min value is positive and max is negative in the raw scans.

Thanks!

**Comment by mich1342** [comment]
Hi @Rudresh172 ,

Just want to check whether if you have run the pointcloud to laserscan node? This package only crates a pcl topic not the laserscan. The pointcloud to laserscan does the conversions

**Comment by Rudresh172** [comment]
Hey @mich1342 ,

The merge_2_scan.launch.py launch file already launches the pointcloud_to_laserscan node. I have done a binary install of the package pointcloud_to_laserscan, since the source install gives some 'tf2_sensor_msgs' error. 
![merger](https://github.com/mich1342/ros2_laser_scan_merger/assets/93994789/6603f546-9f62-426a-8687-96f5ed4e5131)

Further the /cloud_in echo gives an empty data string - 
![cloud_in echo](https://github.com/mich1342/ros2_laser_scan_merger/assets/93994789/d87d54ca-f74a-4f17-afc0-6f9b47d4016f)

**Comment by Rudresh172** [comment]
Hey @mich1342 ,

Just wanted to know if you could track the problem? Or is there any direction that you could point where I should be looking for?

Thanks!

**Comment by mich1342** [comment]
Hi @Rudresh172 , could you try to visualize the point cloud output of the package first?

**Comment by Rudresh172** [comment]
Hey @mich1342 ,

I tried to visualize the pointcloud output, but I can't see anything in Rviz. What should I set the frame_id? I tried both laser and base_link. I also tried the visualize_merge Rviz window, but still everything blank.

![Screenshot from 2023-12-15 15-17-25](https://github.com/mich1342/ros2_laser_scan_merger/assets/93994789/cc277e08-1946-4b98-89e5-0ee5578a777b)

**Comment by mich1342** [comment]
Hi @Rudresh172 ,

have you solved the issue? Would you mind if we do a short online session to discuss and do some trial over this weekend?

Best Regards

michael

**Comment by Rudresh172** [comment]
Hey @mich1342 ,

That would be very helpful to me, but unfortunately I am travelling for the next 3 weeks, so I do not have access to the hardware to perform tests. So please send me your contact details or you can contact me on rudresh172@gmail.com and I would be very grateful to have a call in mid-January if that's okay with you.

Thanks!

**Comment by mich1342** [comment]
Hi @Rudresh172 ,

Just push some update for your use cases to ensure the min and max angle is correct. Please check. Thank you
