### ISSUE TITLE
How is offset calculated

### ISSUE THREAD

**Issue by maksimmasalski** [mich1342/ros2_laser_scan_merger#14]
Hello, 
I'm trying to figure out how offset is calculated, and what is a reference point that offset is using? I noticed that on small values like 0.125, or 0.25 there is no change in rviz ( I was changing Y value). But if I give big value like 1.0, I immediately can see that final /scan visualization changed its position.

**Comment by mich1342** [comment]
Hi, 

All of the offset are calculated from the center of the robot. It is just a simple matrix calculation offseting the coordinates directly. The changes might need some times for the parameters to refresh. Thank you

 Best Regards
 
 Michael

**Comment by maksimmasalski** [comment]
> Hi,
> 
> All of the offset are calculated from the center of the robot. It is just a simple matrix calculation offseting the coordinates directly. The changes might need some times for the parameters to refresh. Thank you
> 
> Best Regards
> 
> Michael

Thanks Mich, yes, I noticed some lagging between rqt parameters change and rviz drawing. Sometimes I needed to restart node to see a refreshed lidar scan position. Now it works well using SLAM ToolBox. I will record video soon

**Comment by mich1342** [comment]
Hi @maksimmasalski ,

Glad to hear that it works for you. May I know your setup and how many packages are you running that you got some noticeable lag from the parameter changes?
