### ISSUE TITLE
Merge 3 lidar_scan topics with 120° interval

### ISSUE THREAD

**Issue by ipa-ych** [mich1342/ros2_laser_scan_merger#15]
Hi,

I am searching for a method to merge 3 lidar_scan topics (the 3 lidar sensors are located on the same plane with same offset to base_link with 120° interval). It seems the ros2_laser_scan_merger only support merging 2 lidar_scan (?). Has the effort been done anywhere to merge 3 or more lidar_scan topics or what is the current progress?

**Comment by mich1342** [comment]
Hi @ipa-ych 

Making it support 3 Lidars actually quite straight forward by adding the third part to the code (subscriber, callbacks, parameters, etc.) by looking at the current state. 

As of now, I am thinking of adding a dynamic number of lidars but have not found lot of use cases that requires more than 2 lidars.

For your use case I believe you could simply modify the source code directly. Thank you.

Best Regards

Michael

**Comment by ipa-ych** [comment]
Hi Michael, 

thanks for the reply. I modified the node for 3 laser_scan and it works for slam & navi. Many thanks!

The only flaw is that all three lasers are shown in color WHITE in rviz despite the given settings. Any idea how should I change the 'Laser' configuration in rviz?
![image](https://github.com/mich1342/ros2_laser_scan_merger/assets/158490112/5684df4c-d2fe-4b11-a67b-664f91f40416)

**Comment by mich1342** [comment]
Hi, nice to hear that. As scan data already merged, they will be displayed as 1 entity (consists only ranges data). If you would like to view the separated color for each laser scan data, please view the pointcloud2 data instead, I believe it should be the cloud_in topic.
