### ISSUE TITLE
Handling 3D data

### ISSUE THREAD

**Issue by tersite1** [mich1342/ros2_laser_scan_merger#16]
Hello. I am a college student who is building my own self-driving car. First of all, I would like to thank you very much for creating this code.

First of all, our goal is to turn two different LIDAR into one publisher.
We have velodyne's vlp-16 lidar and livox lidar and plan to integrate the two and use them for clustering and object detection.

However, among the repo contents you wrote, <Point Cloud to Lasercan> appears to convert 3D LiDAR data into 2D. For object detection, 3D coordinates will also be needed, but LiDAR integration is possible without conversion to 2D. Can’t I proceed with the process?

**Comment by mich1342** [comment]
Hi @tersite1 

Thank you for your interest in this repo. However, this repo is not meant to be made for 3D data. As the name says LaserScan means 2D data. I am not sure what are you gonna use, if it is for Nav2 kind of obstacle avoidance I believe you could achieve it by adding more than 1 pointcloud data source and give a proper TF. Thank you.

**Comment by tersite1** [comment]
> Hi @tersite1
> 
> Thank you for your interest in this repo. However, this repo is not meant to be made for 3D data. As the name says LaserScan means 2D data. I am not sure what are you gonna use, if it is for Nav2 kind of obstacle avoidance I believe you could achieve it by adding more than 1 pointcloud data source and give a proper TF. Thank you.
