### ISSUE TITLE
Timing issue causing Core segmentation fault

### ISSUE THREAD

**Issue by mzuzic-maidea** [mich1342/ros2_laser_scan_merger#3]
I have identified issue whihc causes C segmentation fault and proccess exit code is 11. Since callback to merge scans is at sub1_ and it is calling update_point_cloud_rgb() which is expecting to have laser2_ availabel which is instanced in scan_callback2 it causes segmentaiton error.

I have resolved this issue by adding if(show1_ && laser1_) and if(show2_ && laser2_) .

Can't push to repo to open PR.

**Comment by mich1342** [comment]
Hi @mzuzic-maidea, 

Thank you for your interest in this repo. Could you specify why you could not push to repo to open PR?

**Comment by mzuzic-maidea** [comment]
Hey, @mich1342 , not sure, I got permission denied, message that I am not allowed to push to this repo. My SSH keys are working properly.

**Comment by mich1342** [comment]
Hi @mzuzic-maidea 

Sorry for the late reply, been quite busy with work recently. I have checked the repo settings and should let anyone do pull request. Could you post the error message screen shoot? Thank you

**Comment by mich1342** [comment]
HI @mzuzic-maidea , I have update the repo based on your solutions so that the issue is not hangging to long. Thank you.
